books/urls.py
from django.urls import path
from books.views import (
    get_genre_books,
    get_tag_books,
    add_book,
    search_book,
    delete_book,
    update_book,
    add_comment,
    buy_book,
    favorite_book,
    favorites,
    delete_from_favorites,
    BookListView,
    BookDetailView,
    search_book_by_tags, book_detail, get_all_books, create_book, get_all_genres, get_all_publishers
)


urlpatterns = [
    path("get_genre/<str:title>/", get_genre_books, name="get_genre"),
    path("get_tag/<str:title>/", get_tag_books, name="get_tag_books"),
    path("add_book/", add_book, name="add_book"),
    path("update_book/<int:id>/", update_book, name="update_book_by_id"),
    path("seach_book/", search_book, name="search_book"),

    path("search_book_by_tags/", search_book_by_tags, name="search_book_by_tags"),

    path("delete_book/<int:id>/", delete_book, name="delete_book"),
    path("add_comment/<int:id>/", add_comment, name="add_comment"),
    path("buy_book/<int:id>/", buy_book, name="buy_book"),
    path("favorite/<int:id>/", favorite_book, name="favorite_book"),
    path("favorites/", favorites, name="favorites"),
    path("delete_from_favorites/<int:id>/", delete_from_favorites, name="delete_from_favorites"),

    # HTML
    path("get_books/", BookListView.as_view(), name="books"),
    path("detail_book/<int:pk>/", BookDetailView.as_view(), name="get_book"),

    # JSON API
    path("get_all_books/", get_all_books),
    path("get_book/<int:id>/", book_detail),
    path("create_book/", create_book),
    path("get_all_genres/", get_all_genres),
    path("get_all_publishers/", get_all_publishers)
]

first/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import first, second_func



from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', first),
    path('second/', second_func),
    path('', include('books.urls')),
    path('users/', include('users.urls'))




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return f"Тэг: {self.title}"


class Publisher(models.Model):
    LANGUAGES = (("ru", "Russian"), ("en", "English"), ("fr", "French"))

    title = models.CharField(max_length=50)

    language = models.CharField(max_length=2, choices=LANGUAGES)

    def __str__(self):
        return f"Издание: {self.title} {self.language}"


class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    year = models.IntegerField()
    raiting = models.IntegerField(default=0, null=True, blank=True)

    publisher = models.OneToOneField(
        "Publisher", on_delete=models.DO_NOTHING, default=None, null=True, blank=True
    )

    genre = models.ForeignKey(
        "Genre",
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="books",
    )

    tags = models.ManyToManyField("Tag", related_name="books", blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    image = models.ImageField(default="default.jpg")

    user = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, null=True, blank=True, related_name="books"
    )

    price = models.DecimalField(max_digits=6, decimal_places=2)

    count = models.IntegerField(default=10)

    def __str__(self):
        # строковое представление объекта
        return f"Книга: {self.id} Название: {self.title} Автор: {self.author}"

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"


# первичная запись
class Genre(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return f"Жанр: {self.id}, {self.title}"


class Comment(models.Model):
    content = models.CharField(max_length=300)
    raiting = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")

    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="comments")

    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Комментарий: {self.content}, {self.user.username}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="favorites")

    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="favorites")

    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Добавлено в избранное юзером: {self.user.username} {self.book.title}"

    class Meta:
        verbose_name = "Избранная книга"
        verbose_name_plural = "Избранные книги"

templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить новую книгу</title>
</head>
<body>
    <h3>Страница с добавлением новой книги</h3>
    <form action="{% url 'add_book' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <p>{{ field.label_tag }} {{ field }}</p>
        {% endfor %}
        <input type="submit" value="OK">
    </form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>

<form action="{% url 'search_book' %}" method="get" style="width: 300px; margin: 20px;">
    {% csrf_token %}
    <input class="form-control" placeholder="Введите название книги" type="text" name="title">
    <input class="form-control" placeholder="Введите жанр" type="text" name="genre">
    <input class="form-control" placeholder="Введите цену до" type="number" name="price_lt">
    <input type="submit" value="OK">
</form>

{% block content %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ book.title }}
{% endblock %}

{% block content %}

    {% if book.image %}
    <img style="width: 100px; height: 100px" src="{{ book.image.url }}">
    {% endif %}

    <h1>{{ book.title }}</h1>
    <h2>{{ book.author }}</h2>
    <br>
    <p>Год: {{ book.year }}</p>
    <p>Рейтинг: {{ book.raiting }}</p>

    <p>Издатель: {{ book.publisher.title }}</p>
    <p>Язык: {{ book.publisher.get_language_display }}</p>

    {% if book.genre %}

    <p>Жанр: {{ book.genre.title }}</p>

    {% else %}

    <p>Жанр: не указан</p>

    {% endif %}

    <p>Время публикации на сайте: {{ book.created_at }}</p>

    <p>Теги: </p>

    {% for tag in book.tags.all %}
        <b> <a href="{% url 'get_tag_books' tag.title %}"> {{ tag.title }} </a> </b>
    {% endfor %}

    <p>Добавил на сайт: {{ book.user.username }}</p>

    <p>Цена: {{ book.price }}</p>

    {% if book.count > 0 %}

    <a href="{% url 'buy_book' book.id %}">Купить книгу</a>

    {% else %}

    <h3>Книг на складе не осталось</h3>

    {% endif %}

    {% if request.user.is_authenticated and show_favorite_button %}

    <a href="{% url 'favorite_book' book.id %}">Добавить в избранное</a>

    {% else %}

    <p>Добавлено в избранное</p>

    {% endif %}

    <br>
    <br>
    <hr>

    {% if request.user.username == book.user.username %}

    <a href="{% url 'update_book_by_id' book.id %}">Редактировать</a>
    <a href="{% url 'delete_book' book.id %}">Удалить книгу</a>

    {% endif %}

    <br>
    <br>

    {% if request.user.is_authenticated %}
        <form action="{% url 'add_comment' book.id %}" method="post">
                {% csrf_token %}

                <textarea name="comment"></textarea>

                <input type="submit" value="Добавить комментарий!">
        </form>
    {% endif %}

    <br>

    {% for comment in book.comments.all %}
        <div style="border: 1px solid black; width: 300px; margin-bottom: 10px; padding: 10px;">
            <p>{{ comment.content }}</p>
            <p>{{ comment.user }}</p>
            <p>{{ comment.date_created }}</p>
        </div>

    {% endfor %}

{% endblock %}

templates/favorites.html
{% extends 'base.html' %}

{% block title %} Избранное {% endblock %}


{% block content%}
<a href="{% url 'books' %}">На главную</a>
    {% if favorites%}

    {% for favorite in favorites %}
        <div style="border: 1px solid black; width: 500px; margin: 10px; padding: 10px;">
            <h3><a href="{% url 'get_book' favorite.book.id %}">{{ favorite.book.title }}</a></h3>
            <p>Автор: {{ favorite.book.author }}</p>
            <p>Рейтинг: {{ favorite.book.raiting }}</p>
            <p>Год выпуска: {{ favorite.book.year }}</p>
            <p>Цена: {{ favorite.book.price }}</p>
            <hr>
            <a href="{% url 'delete_from_favorites' favorite.book.id %}">Убрать из избранного</a>
        </div>
    {% endfor %}

    {% else %}
    <h2>Вы еще не добавили ни одной книги в избранное</h2>
    {% endif %}
{% endblock %}

templates/genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Жанр {{genre.title}}</title>
</head>
<body>
    <h1>{{genre.title}}</h1>
    {% for book in genre.books.all %}
        <p>{{ book.id }}</p>
        <p>{{ book.title }}</p>
        <p>{{ book.author }}</p>
    <br>
    {% endfor %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная по книгам
{% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}

    <h1>Вы успешно вошли как {{ request.user.username }} </h1>
    <h3><a href="{% url 'favorites' %}">Избранное</a></h3>
    <h3><a href="{% url 'logout' %}">Выход</a></h3>

    {% else %}

    <a href="{% url 'register' %}">Регистрация</a>
    <a href="{% url 'login' %}">Вход</a>

    {% endif %}

    <h1>
        Список книг
    </h1>

    {% for book in books %}
        <p>
            Название: <a href="{% url 'get_book' book.id %}">
                {{book.title}}
            </a>
        </p>
        <p>Автор: {{book.author}}</p>
        <p>Жанр: {{book.genre.title}}</p>
        <p>Год: {{book.year}}</p>
        <p>Цена: {{ book.price }}</p>
        <br>

    {% endfor %}

    <a href="{% url 'add_book' %}">Добавить книгу</a>
{% endblock %}

templates/login_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
</head>
<body>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}

        {% for field in form %}
            <p>{{ field.label_tag }} {{ field }}</p>
        {% endfor %}

        <input type="submit" value="OK">
    </form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация пользователя</title>
</head>
<body>

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}

        {% for field in form %}
            <p>{{ field.label_tag }} {{ field }}</p>
        {% endfor %}

        <input type="submit" value="OK">
    </form>

</body>
</html>

templates/search_book.html
{% extends 'base.html' %}

{% block title %}
    Поиск
{% endblock %}

{% block content%}

    <h1>Поиск книг</h1>

    {% if books %}

    <h3>{{ result_string }}</h3>

    {% for book in books %}
        <p>
            Название: <a href="{% url 'get_book' book.id %}">
                {{book.title}}
            </a>
        </p>
        <p>Автор: {{book.author}}</p>
        <p>Жанр: {{book.genre.title}}</p>
        <p>Год: {{book.year}}</p>
        <p>Цена: {{book.price}}</p>
        <br>

    {% endfor %}

    {% else %}
        <h3>Книг с такими фильтрами нет!</h3>
    {% endif %}

{% endblock %}

templates/tag_detail.html
{% extends 'base.html' %}

{% block title %}Фильтрация по тегу{% endblock %}

{% block content %}

<form action="{% url 'search_book_by_tags' %}" method="get" style="width: 300px; margin: 20px;">
    {% csrf_token %}
    <input placeholder="Введите теги" class="form-control" name="tags_input">
    <input type="submit" value="OK">
</form>

{% if messages %}

    {% for message in messages %}
       <div class="alert alert-danger" role="alert">
           {{ message }}
       </div>
    {% endfor %}

{% endif %}

    <h1>Тег: {{ tag.title }}</h1>
    <h3>Все книги с таким тегом: </h3>

    {% for book in tag_books %}
        <p>{{ book.title }}</p>
    {% endfor %}

{% endblock %}

templates/update_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Обновить книгу</title>
</head>
<body>
    <h1>Обновление книги</h1>

    <h2>{{book.title}}</h2>

    <form action="{% url 'update_book_by_id' book.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <p>{{ field.label_tag }} {{ field }}</p>
        {% endfor %}
        <input type="submit" value="OK">
    </form>
</body>
</html>